feature/unittest-infoProfile
TuanAnh2k1/CreditLoan pull request #2
Opened 2023-07-13 10:16 UTC by TuanAnh2k1

- Unit test
- form cảnh báo các trường bắt buộc.
- custom keyboard số tiền vay dự kiến, sđt, căn cước, thời gian vay
- check điều kiện khi submit

2023-07-17 02:43 UTC, TuanAnh2k1 commented
task
- https://trello.com/c/RYhEFGOl
- https://trello.com/c/sLBHobER
- https://trello.com/c/Zoe2eYQ8

2023-07-17 07:57 UTC, longph2023 commented on Validate/DropdownFunctions.ts
> +  const validProfessions = ['Lập trình viên', 'Kỹ sư', 'Giáo viên'];
hạn chế khai bào const trong hàm nhé
nên để vào object AppConstants

2023-07-17 07:57 UTC, longph2023 commented on Validate/DropdownFunctions.ts
> +  const validIncomeLevels = [
hạn chế khai bào const trong hàm nhé
nên để vào object AppConstants

2023-07-17 08:46 UTC, longph2023 requested changes

2023-07-17 08:46 UTC, longph2023 commented on src/screens/FormRegister/FormRegister.tsx
> +    const url = 'https://ebank.bidv.com.vn/DKNHDT/term.htm';
Chỗ url cũng đặt vào AppConstants hawojc Base nhé

2023-07-17 08:46 UTC, longph2023 commented on src/store/actions/formActions.ts
> +        'https://musicfivestar.onrender.com/register',
Chỗ này cũng cho vào Constants hoặc base
Anh suggest cho vào base hơn với cả hình như chưa chia môi trường prod, dev thì phải

2023-07-18 08:58 UTC, longph2023 approved these changes

2023-07-18 08:58 UTC, merged